# Generated by Django 5.1.11 on 2025-07-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='numero_celular',
            new_name='celular',
        ),
    ]
