# Generated by Django 5.1.11 on 2025-07-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_alter_curso_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
